### ISSUE TITLE
missing percentile scores (Webcdi North American English) from infantstudiesubc

### ISSUE THREAD

**Issue by angelinetsui** [manybabies/mb1-cdi-followup#13]
@melsod , I am double checking the codes and I noticed that infantstudiesubc has collected North American English CDI via webcdi but they don't have percentile scores, as a result, we lost 26 data for the first model of the mixed-level analysis. Is there a way to contact infantstudiesubc for missing data or we need to calculate that on our own? Please advise

**Comment by melsod** [comment]
Weird. I found the file in the Drive folder - not sure why it didn't make it into github (I know it came in a little late, but I thought we'd resovled all the missing data issues). I guess we need to get the daily percentiles for these infants as well?

If you find anything else missing, you can check here: https://drive.google.com/drive/u/0/folders/0B_XEqE_IQePJSG9nM1JnVEtJUEk?resourcekey=0-m-B9RFWedZzGuz2vYESQzA

**Comment by angelinetsui** [comment]
Done, I re-entered the missing data, but now we have a problem as there are data that has percentile "<1". In this case, what should we deal with these data? Should we change "<1" percentile to 0? @melsod

**Comment by angelinetsui** [comment]
never mind, R seems to be able to analyze "<1" data???

**Comment by angelinetsui** [comment]
Sorry for multiple changes here, but I just found Arthur's codes in 02.Rmd that he has changed "<1" percentile score "0" for analysis.

**Comment by angelinetsui** [comment]
We will need to make a note in the RR for this change, but I think this is very reasonable
