### ISSUE TITLE
weltentdecker-zurich sub-id mismatches

### ISSUE THREAD

**Issue by melsod** [manybabies/mb1-cdi-followup#2]
From Anja:

mb12516 did not show up at the date of the eyetracking study but filled in the questionnaire
mb12676 was later on excluded for the eyetracking data
mb12690 was later on excluded for the eyetracking data
mb12755 was a pilot child for the experimenter
mb13178 was later on excluded for the eyetracking data
mb13505 was a pilot child for the experimenter

---
For the pilots, these can easily be just excluded. 

We will need to exclude all the participants who fussed out or for whom their data were excluded (not just for this lab). However, I'm curious why there was no "match" - or are we only matching on the post-exclusions sample?

We'll just need to be consistent in how we report this.

**Comment by respatte** [comment]
Those have no match in the full unprocessed IDS data either. They might have been excluded beforehand though, which would explain why they are flagged in our script. They will remain flagged but this is now documented in the script, and those infants are not included in the final dataset.
