### ISSUE TITLE
babylab-brookes

### ISSUE THREAD

**Issue by melsod** [manybabies/mb1-cdi-followup#3]
from Nayeli:

Participant mb17 was tested outside the age bin, she was too young (82 days) that was why her data was not submitted.
Similarly, participants mb124 and 143 were too old (462 and 465 days).

So these should be exclusions as well. Note that we do have some "out of range" babies in the original sample, but only in cases where they were still within the 3-15 month range.

**Comment by respatte** [comment]
This is now documented in the script. Note that `mb143` appeared in our data as `mb43`, but this does not matter since we don't use their data.
