### ISSUE TITLE
issue in Main exploratory analysis

### ISSUE THREAD

**Issue by mohmdsh** [manybabies/mb1-cdi-followup#36]
I am working on our virtual image of the project. Everything was working well on my local machine, but when I ran the virtual image "the Main exploratory analysis" lines 61-66 gave the following error:

Error in if (data$vocabulary_percentile > 1) { : 
  the condition has length > 1

Again, I did not have in my local machine! I wonder if you got the same error after the latest changes!

**Comment by munozalvalu** [comment]
Hi,

Not sure when it changed but the condition inside needed to wrapped in any(). I've put it now back now. It should work again. Thanks for catching this!

Best,
Luis
