### ISSUE TITLE
unlvmusiclab subid

### ISSUE THREAD

**Issue by respatte** [manybabies/mb1-cdi-followup#6]
Participant `unlvmusiclab:run001` in the CDI data was apparently a pilot participant in the IDS dataset (`unlvmusiclab:run001pilot`). Do we want to include them in the analysis? Are we sure that we do not have more pilot participants without knowing about it?

**Comment by melsod** [comment]
exclude from the analysis. Not sure how this snuck through - the processing for MB1 should have identified and excluded all the pilots, and they should all be marked as "pilot". It's worth at least a scan through our dataset to ensure there aren't any other rows marked as "pilot" in any of the fields.

**Comment by respatte** [comment]
Indeed this participant does not have any IDS data in the original file, which makes it be excluded automatically in script 02. To keep things consistent, I just renamed it from `run001` to `run001pilot` in the CDI data as the scope of script 01 is not to exclude participants.
